spring:
  datasource:
    url: jdbc:mysql://localhost/shop?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    hikari:
      maximum-pool-size: 10

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

logging:
  level:
    root: info

